development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:760ec6645a85524bed469c0cd13deb92@pearlfish.redistogo.com:9625/
  channel_prefix: fam-dash_production
